version: '3'
services:
  dentistry:
    image: bitnami/postgresql:11
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dentistry

  app:
    image: dmitrysursin/springboot-react-fullstack:latest
    ports:
      - 8080:8080
    depends_on:
      - dentistry
    environment:
      - DATABASE_HOST=dentistry
      - DATABASE_PORT=5432
      - DATABASE_NAME=dentistry
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dentistry:5432/dentistry
